import { RefObject, useEffect } from "react"

// NOTE: this was totally generated by GPT-4, don't fully understand it yet
export function useInfiniteScroll<T extends HTMLElement>(
  ref: RefObject<T>,
  callback: () => void,
  threshold: number = 0
) {
  useEffect(() => {
    if (!ref.current) {
      return
    }

    const observer = new IntersectionObserver(
      (entries) => {
        const firstEntry = entries[0]

        if (firstEntry.isIntersecting) {
          callback()
        }
      },
      { threshold }
    )

    observer.observe(ref.current)

    return () => {
      observer.disconnect()
    }
  }, [ref, callback, threshold])
}
