import WindowAI from "@components/WindowAI";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-6">
        <div className="col-span-6">
          <div className="flex h-full w-full flex-col">
            <WindowAI />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
